#!/bin/bash

if [ -e /etc/os-release ]; then
  source /etc/os-release
  if [ "$ID_LIKE" == "debian" ]; then
    apt-get update
    echo "deb https://apt.dockerproject.org/repo ${ID}-$(lsb_release --codename | awk '{ print $2 }') main" | tee /etc/apt/sources.list.d/docker.list
    apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    apt-get update
    apt-get install -y docker-engine
    service docker start
  fi
fi

